### PR TITLE
Update README and INSTALL, Issue # 2 Fixed 

### LINKED ISSUE #2: Run Installation Test and Update Docs
### In Install.md:

- Curl installation for releases build(both .zip and .tar.gz) - should include unpacking them and moving them to the nvim folder
- Uninstall(For MacOS and Linux) - Checkout astrovim and nvchad and lunarvim

Check if all the commands are running fine!

### In Readme:

Include a section of "Custom Configuration" in the Readme
Here mention how a user can have a custom configuration, like they should create a folder inside lua and update the entrance level init.lua file to take effect.

### PR DESCRIPTION
**Pull request by AHSANATIQ98**
### Summary:

- [ ] Bug Fix 🐛
- [ ] New Feature ✨
- [x] Documentation Update 📝
- [ ] Custom 🔧

---

### 🐛 Bug Fix:

1. **Bug**: (e.g., Fixed issue where `options.lua` would crash if a specific plugin was missing.)
   **Proposed Solution**: (e.g., Changing the mouse property/line 23 would work)
   **Is it OS/Terminal Specific**: (e.g., macOS and kitty terminal)

2. **Bug**: (e.g., Fixed issue where `options.lua` would crash if a specific plugin was missing.)
   **Proposed Solution**: (e.g., Changing the mouse property/line 23 would work)
   **Is it OS/Terminal Specific**: (e.g., macOS and kitty terminal)

---

### ✨ New Feature (Plugins):

1. **New Plugin**: (e.g., `nvim-tree` plugin)
   **Plugin Use**: (e.g., `nvim-tree` allows users to explore and manage files directly within Neovim.)
   **Plugin Configuration**: (e.g., Added Custom/Ready-made Configuration - to the plugin_config folder)
   **Plugin Link**: (e.g., https://github.com/nvim-tree/nvim-tree.lua)

2. **New Plugin**: (e.g., `nvim-tree` plugin)
   **Plugin Use**: (e.g., `nvim-tree` allows users to explore and manage files directly within Neovim.)
   **Plugin Configuration**: (e.g., Added Custom/Ready-made Configuration - to the plugin_config folder)
   **Plugin Link**: (e.g., https://github.com/nvim-tree/nvim-tree.lua)

---

### 📝 Documentation Updates:

- [x] Updated README
- [ ] Updated Wiki
- [x] Other Documentation (INSTALL):

---

### 🔧 Additional Information (Custom):

---

### 🔗 Related Issues (if any):

---

### ✅ Checklist:

- [x] My code adheres to the code style of this project.
- [x] I have run the appropriate tests for this change.
- [x] I have updated the documentation (if needed).
- [x] My PR references any relevant issues (if applicable).
- [ ] Breaking changes?

### CODE REVIEW

**Comment by prrockzed** [comment]
I have added some comments to the file. Do check those out. If the config was running fine after the installation then it is all ok. Just do the changes i suggested.

**Comment by AHSANATIQ98** [comment]
Unfortunately, I dont know Lua. I just updated readme.md and install.md as text files.

**Comment by prrockzed** [comment]
Ok. Then do the changes changes for markdown files only as suggested like adding of custom configuration in the content section of the readme and some changes in the headings. These are purely markdown related things and no knowledge of lua is required.

**Comment by AHSANATIQ98** [comment]
where i can find those files. I am totally beginner to github..

**Comment by AHSANATIQ98** [comment]
Custom configuration is already there as heading.

**Comment by prrockzed** [comment]
As i said earlier, add custom configuration to the content section of readme file. 
And in the install.md file, make changes as suggested: Make the installation as heading 3(###) and successive headings as heading 4(####). Keep Uninstallation Heading as ##.

These changes are suggested based on the work you have done above. You yourself made changes in install.md and readme.md files, so there should be no problem in finding the files.

**Comment by AHSANATIQ98** [comment]
My bad, i got.and also done..

**Pull request merged**
