### PR TITLE
Additon of All Contributors | Issue #6

### LINKED ISSUE #12: add contributing.md
A CONTRIBUTING.md file, in your open source repository or site, provides potential project contributors with a short guide to how they can help with your project or study group

### PR DESCRIPTION
**Pull request by Shariq2003**
### Summary:

I have added all the contributors in readme.md file to give them appreciation.
Completed #6 

- [ ] Bug Fix 🐛
- [ ] New Feature ✨
- [X] Documentation Update 📝
- [ ] Custom 🔧

---

### 🐛 Bug Fix:

1. **Bug**: (e.g., Fixed issue where `options.lua` would crash if a specific plugin was missing.)
   **Proposed Solution**: (e.g., Changing the mouse property/line 23 would work)
   **Is it OS/Terminal Specific**: (e.g., macOS and kitty terminal)

2. **Bug**: (e.g., Fixed issue where `options.lua` would crash if a specific plugin was missing.)
   **Proposed Solution**: (e.g., Changing the mouse property/line 23 would work)
   **Is it OS/Terminal Specific**: (e.g., macOS and kitty terminal)

---

### ✨ New Feature (Plugins):

1. **New Plugin**: (e.g., `nvim-tree` plugin)
   **Plugin Use**: (e.g., `nvim-tree` allows users to explore and manage files directly within Neovim.)
   **Plugin Configuration**: (e.g., Added Custom/Ready-made Configuration - to the plugin_config folder)
   **Plugin Link**: (e.g., https://github.com/nvim-tree/nvim-tree.lua)

2. **New Plugin**: (e.g., `nvim-tree` plugin)
   **Plugin Use**: (e.g., `nvim-tree` allows users to explore and manage files directly within Neovim.)
   **Plugin Configuration**: (e.g., Added Custom/Ready-made Configuration - to the plugin_config folder)
   **Plugin Link**: (e.g., https://github.com/nvim-tree/nvim-tree.lua)

---

### 📝 Documentation Updates:

- [X] Updated README
- [ ] Updated Wiki
- [ ] Other Documentation (please specify):

---

### 🔧 Additional Information (Custom):
image

---

### 🔗 Related Issues (if any):

---

### ✅ Checklist:

- [X] My code adheres to the code style of this project.
- [X] I have run the appropriate tests for this change.
- [X] I have updated the documentation (if needed).
- [] My PR references any relevant issues (if applicable).
- [] Breaking changes?

### CODE REVIEW

**Comment by prrockzed** [comment]
First remove the eye emoji(👀) from the contributors heading as this messes with with linking. And as I told, add 'Contributors' in the content section of the readme as well, just above 'Support'.

**Comment by Shariq2003** [comment]
> First remove the eye emoji(👀) from the contributors heading as this messes with with linking. And as I told, add 'Contributors' in the content section of the readme as well, just above 'Support'.

@prrockzed Check now

**Comment by prrockzed** [comment]
I was going through the contributors section, when i spotted 'Ratna Supermarket' in nvimDev!
Do please check before copy pasting.

Also a small change: remove the line which says give a star to the project, coz i have already added it in the 'Support' section. And also remove the bullet point from 'Our Contributors' section(bcoz after removing the star line, there will only be one line left).

**Comment by prrockzed** [comment]
Ok. Merging the PR and closing the issue.

**Pull request merged**
