### PR TITLE
Updated nightly_git.lua

### LINKED ISSUE #30: update nightly_git.lua
1. Error Handling Enhancements:
Non-zero Git Exit Codes: Currently, exit codes are used, but more specific error messages could be given depending on the failure mode (e.g., network issues, conflicts during a pull).
Error Handling in jobstart: You can add handling for cases where the jobstart itself fails to launch or run a Git command. Right now, you’re handling failures only in the command results.
2. Code Readability and Modularity:
Separate Git Commands into Functions: You could refactor the git pull, git add, and git commit steps into individual functions to improve readability and allow for easier maintenance.
Simplify Callbacks: Using nested callbacks can get tricky. You could use a task queue or a promise-like structure to manage async Git tasks in sequence.
3. User Experience Enhancements:
Abort on Failure: After notifying the user about a failed Git operation (e.g., pull or commit failure), the script should offer an option to retry or cancel further actions rather than silently failing.
Customizable Auto-Commit Messages: Allow the user to define a default auto-commit message instead of hardcoding "Auto-commit: Staging changes before rebase".
4. Git Status Handling Improvements:
Distinguish between Untracked and Staged Changes: The current implementation doesn’t distinguish between various types of changes (modified, staged, untracked). Use git status --porcelain output to provide more nuanced feedback, like "Untracked files detected" or "Staged but not committed changes".

### PR DESCRIPTION
**Pull request by Charvi-14**
### Summary:

- [x] New Feature ✨

### ✨ New Feature :

1) Error Handling Enhancements:

- Non-zero Git Exit Codes: Currently, exit codes are used, but more specific error messages could be given depending on the failure mode (e.g., network issues, conflicts during a pull).
- Error Handling in jobstart: You can add handling for cases where the jobstart itself fails to launch or run a Git command. Right now, you’re handling failures only in the command results.

2) Code Readability and Modularity:

- Separate Git Commands into Functions: You could refactor the git pull, git add, and git commit steps into individual functions to improve readability and allow for easier maintenance.
- Simplify Callbacks: Using nested callbacks can get tricky. You could use a task queue or a promise-like structure to manage async Git tasks in sequence.

3) User Experience Enhancements:

- Abort on Failure: After notifying the user about a failed Git operation (e.g., pull or commit failure), the script should offer an option to retry or cancel further actions rather than silently failing.
- Customizable Auto-Commit Messages: Allow the user to define a default auto-commit message instead of hardcoding "Auto-commit: Staging changes before rebase".

4) Git Status Handling Improvements:
Distinguish between Untracked and Staged Changes: The current implementation doesn’t distinguish between various types of changes (modified, staged, untracked). Use git status --porcelain output to provide more nuanced feedback, like "Untracked files detected" or "Staged but not committed changes".
---

### 🔗 Related Issues (if any):

Fixes #30 

---

### ✅ Checklist:

- [x] My code adheres to the code style of this project.
- [x] I have run the appropriate tests for this change.
- [x] I have updated the documentation (if needed).
- [x] My PR references any relevant issues (if applicable).
- [ ] Breaking changes?

### CODE REVIEW

**Comment by prrockzed** [comment]
Ha e u fully checked the code and re run with appropriate tests?

**Comment by Charvi-14** [comment]
I checked it locally

Although I recommend you to check it as well

Regards

**Comment by prrockzed** [comment]
Ok. I asked like, did u go to previous commit via 'git reset --hard' and then did you try with the Updatenvimdev command and it functioned as you wished it would?

**Comment by Charvi-14** [comment]
Yes, it worked!

**Comment by Charvi-14** [comment]
Hey, are we going forward with the level3 issue as well?

**Comment by Charvi-14** [comment]
Hey, are we going forward with the level3 issue as well? @prrockzed

**Pull request merged**
