### PR TITLE
Update Contributors Section in README 

### LINKED ISSUE #9: Add GitHub Action that automatically displays all contributors in the README
We can add a file in workflows to add the contributors automatically to readme which basically enhaces the repo visibility
Hey @prrockzed  please assign this task to me with level tag

### PR DESCRIPTION
**Pull request by shubhagarwal1**
This PR updates the Contributors section in the README.md file to include only the names of contributors without their GitHub usernames. The update is performed automatically using a GitHub Actions workflow that extracts contributor names from the commit history. The following changes have been made:

Modified the script to normalize contributor names and eliminate username references.
Ensured that duplicate names are not listed in the Contributors section.
The update process is scheduled to run on every commit push, ensuring the README remains current with the latest contributions.
fix #9

### CODE REVIEW

**Comment by prrockzed** [comment]
As you can see in the readme, it already has an automatic contributor display. Hence i don't think your work is any different.

**Comment by shubhagarwal1** [comment]
> As you can see in the readme, it already has an automatic contributor display. Hence i don't think your work is any different.

the code in the readme reads the user form the github itself and shows them on the github only 
also the names of the contributors are not stored hadcodedly anywhere with that code, my ocde will add the list of contributors and that will be the part of the readme file

**Comment by prrockzed** [comment]
Ok, i get your point. Resolve all the merge conflicts and the readme should look exactly as before, that is, it should at the place where it is in readme section and the link in the content should direct to the contribution section. Also it should have the same content as before.

**Comment by prrockzed** [comment]
Are you still working on the issue? Please answer within a day.

**Comment by prrockzed** [comment]
I have told this previously, that the readme should look like before, you have to only change what's inside the contributors section, but you have added a new contributors section. Now there are two contributors section. Does this make any section? Attaching a preview of the readme. Please first take a look at the readme yourself, before commenting here. Make sure everything is right.
Screenshot 2024-10-11 at 3 35 21 PM

**Comment by shubhagarwal1** [comment]
i am so sorry for this unreviewed thing just the problem here is i have merged the branches and the changes were not consistent l, i will make it right, can i raise anither issue or should i work in this to fix this, please allow meto fix this

**Comment by prrockzed** [comment]
okay. Don't raise another issue. You can change it here, or if you want to make another pull request then go ahead(but before doing that, close off this pull request).

**Comment by shubhagarwal1** [comment]
@prrockzed I have another PR, kindly review.

**Comment by prrockzed** [comment]
Do you just commit and come to comment here? I mean review your code before commenting here. I have told this many times and still you don't understand this line: The readme section should look exactly as it was before. Please read my comments over and over(if you don't understand) before committing/commenting here. Have you even previewed your own readme.md file(which you changed)? Am attaching a screenshot of your changes here

Screenshot 2024-10-12 at 12 08 25 PM

I mean how can someone even keep two contributors section? Does that even make sense?
As i told earlier, the readme should look exactly like before. And you have moved the contributors section from above support section to the last section. Also you have remove the horizontal line after the custom configuration section. This type of work isn't expected.
I am expecting a proper response next time. And comment here, only if you feel you have done your job in a good way.

**Comment by prrockzed** [comment]
The readme simply looks like this(below image). You are mixing up the sections here and there.

Screenshot 2024-10-12 at 12 19 26 PM

Our contributors section, then Support and then Acknowledgement section. This is the final time i am saying this. You comment here, when everything is properly done.

**Comment by shubhagarwal1** [comment]
> The readme simply looks like this(below image). You are mixing up the sections here and there.
> 
> Screenshot 2024-10-12 at 12 19 26 PM
> Our contributors section, then Support and then Acknowledgement section. This is the final time i am saying this. You comment here, when everything is properly done.

hey @prrockzed i am not abel to understand, beacuse our contrbutors will only show profile of the contributors and contributor section will show the names which will stay in read me 
should i make the change where under our contributor i add teh code of contributors name, will that work.

**Comment by prrockzed** [comment]
Currently the readme uses contrib.rocks to fetch the contributors names(just check current readme.md page). I thought you will remove the dependency of contrib.rocks and add github actions in its place.

What i want is that the contributors profile pic should be there. Yes, you have to add your code in the 'Our Contributors' section only, i never mentioned to create a new section(as i said why will anyone have 2 contributors section).

**Main Idea** - If you can add your code in the 'Our Contributors' section and remove the dependency of contrib.rocks using Github Action, and at the same time the contributors profile pic should be displayed rather than their names. If you can do this, then go ahead.

**Comment by prrockzed** [comment]
I am closing this pr bcoz of inactivity. If you feel you have made the changes as suggested above, make another pull request.

**Pull request closed without merging**
